# vim: set expandtab shiftwidth=2 tabstop=8 textwidth=0 filetype=yaml:

.templates_sha: &template_sha 3a2bcd49a2a6a34a5fdd35a7fc8c8f9246c0bffc

include:
  - project: 'freedesktop/ci-templates'
    ref: *template_sha
    file:
      - '/templates/fedora.yml'
      - '/templates/ci-fairy.yml'
  - template: Security/SAST.gitlab-ci.yml

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'push'

stages:
  - prep             # prep work like rebuilding the container images if there is a change
  - build            # for actually building and testing things in a container
  - test
  - deploy

variables:
  FDO_UPSTREAM_REPO: libevdev/udev-hid-bpf
  FEDORA_VERSION: 39
  FEDORA_RELEASE_VERSION: 37
  FEDORA_PACKAGES: 'cargo clang elfutils-libelf-devel git-core rustfmt systemd-devel xz zlib-devel'
  FEDORA_TAG:  '2023-11-11.0'
  RUST_BACKTRACE: '1'

.policy:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  # cancel run when a newer version is pushed to the branch
  interruptible: true


#################################################################
#                                                               #
#                          prep stage                           #
#                                                               #
#################################################################

fail-if-fork-is-not-public:
  stage: prep
  script:
    - |
      if [ $CI_PROJECT_VISIBILITY != "public" ]; then
           echo "*************************************************************************************"
           echo "Project visibility must be set to 'public'"
           echo "Change this in $CI_PROJECT_URL/edit under 'Visibility, project features, permissions'"
           echo "*************************************************************************************"
           exit 1
      fi
  except:
    - main@$FDO_UPSTREAM_REPO

#
# Verify that commit messages are as expected, signed-off, etc.
#

check-commit:
  extends:
    - .fdo.ci-fairy
  stage: prep
  script:
    - ci-fairy check-commits --signed-off-by --junit-xml=results.xml
  except:
    - main@$FDO_UPSTREAM_REPO
  variables:
    GIT_DEPTH: 100
  artifacts:
    reports:
      junit: results.xml


#
# Build distribution-specific images used by the jobs in the build stage
#

fedora@container-prep:
  extends:
    - .fdo.container-build@fedora
    - .policy
  stage: prep
  variables:
    GIT_STRATEGY: none
    FDO_DISTRIBUTION_VERSION: $FEDORA_VERSION
    FDO_DISTRIBUTION_PACKAGES: $FEDORA_PACKAGES
    FDO_DISTRIBUTION_TAG: $FEDORA_TAG


fedora-release@container-prep:
  extends:
    - fedora@container-prep
  variables:
    FDO_DISTRIBUTION_VERSION: $FEDORA_RELEASE_VERSION


#################################################################
#                                                               #
#                       build stage                             #
#                                                               #
#################################################################

.build@template:
  extends:
    - .policy
  stage: build
  script:
    - cargo build
    - cargo test
  dependencies: []


.fedora-build@template:
  extends:
    - .fdo.distribution-image@fedora
    - .build@template
  variables:
    FDO_DISTRIBUTION_VERSION: $FEDORA_VERSION
    FDO_DISTRIBUTION_TAG: $FEDORA_TAG
  dependencies:
    - fedora@container-prep


cargo build and test:
  extends:
    - .fedora-build@template


cargo fmt:
  extends:
    - .fedora-build@template
  script:
    - cargo fmt --check


#################################################################
#                                                               #
#                        test stage                             #
#                                                               #
#################################################################

sast:
  stage: test


#################################################################
#                                                               #
#                       deploy stage                            #
#                                                               #
#################################################################

make release:
  extends:
    - .fedora-build@template
  stage: deploy
  variables:
    FDO_DISTRIBUTION_VERSION: $FEDORA_RELEASE_VERSION
  script:
    - ./make_release.sh
  artifacts:
    paths:
      - udev-hid-bpf*.tar*
  dependencies:
    - fedora-release@container-prep


pages:
  extends:
    - .fdo.ci-fairy
  stage: deploy
  script:
    - pip3 install sphinx sphinx-rtd-theme myst-parser
    - sphinx-build -b html doc public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
